---
title: "Karan_TS_Exp"
output: html_document
date: "2024-05-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(ggplot2)
library(lubridate)
library(dplyr)
library(forecast)
library(CausalImpact)
library(tseries)
library(zoo)
library(prophet)
```

```{r}
setwd("D:/University of Chicago/Courses/ADSP 31006 IP02 Time Series Analysis and Forecasting/Final Project")
```

```{r pressure, echo=FALSE}
tmp <- read.csv("CTA_-_Ridership_-_Daily_Boarding_Totals_20240512.csv")
tmp$service_date <- as.Date(tmp$service_date, format="%m/%d/%Y")
data <- tmp[!duplicated(tmp$service_date), ]
head(data)
```

## Aggreagting by month to get bus rides

```{r}
data_monthly_bus <- data %>%
  group_by(month = as.yearmon(service_date)) %>%
  summarise(bus_total = sum(bus, na.rm = TRUE))

head(data_monthly_bus)
```

```{r}
start = as.yearmon("Jan 2001")
end = as.yearmon("Feb 2024")
pre_covid <- c(start, as.yearmon("Feb 2020"))
post_covid <- c(as.yearmon("Mar 2020"), end)
```

```{r}
# Creating a dataframe for Prophet
prophet_data <- data_monthly_bus %>%
  filter(month >= start & month <= end) %>%
  rename(ds = month, y = bus_total) 

head(prophet_data)
```


```{r}
# Splitting the data into pre-COVID and post-COVID periods
pre_covid_data <- prophet_data %>%
  filter(ds < as.yearmon("Mar 2020"))

post_covid_data <- prophet_data %>%
  filter(ds > as.yearmon("Mar 2020"))
```

```{r}
prophet_model_pre_covid <- prophet(
  yearly.seasonality = TRUE,
  weekly.seasonality = TRUE,
  daily.seasonality = FALSE,
  holidays = NULL
)
prophet_fit_pre_covid <- fit.prophet(prophet_model_pre_covid, pre_covid_data)
```

```{r}
summary(prophet_fit_pre_covid)
```


```{r}
# Forecasting post-COVID period
forecast_post_covid <- predict(prophet_fit_pre_covid, post_covid_data)
rmse <- sqrt(mean((forecast_post_covid$yhat - post_covid_data$y)^2))
mse <- mean((forecast_post_covid$yhat - post_covid_data$y)^2)
mape <- mean(abs((forecast_post_covid$yhat - post_covid_data$y) / post_covid_data$y)) * 100
cat("RMSE:", rmse, "\n")
cat("MSE:", mse, "\n")
cat("MAPE:", mape, "%\n")
```


